name: Update Image Tag in GitOps Repository

on:
  workflow_run:
    workflows: ["Build image"]
    branches: [main]
    types:
        - completed

jobs:
    update-image-tag:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        steps:
            - name: "GitOps - Update Image Tag"
              uses: adwert-it/gitops-image-update@v1
              with:
                    REPOSITORY_NAME: 'AdWert-IT/infrastructure'
                    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                    BRANCH: "master"
                    VALUES_FILE_PATH: 'deployments/helmCharts/projects/richtungswechsler/values.yaml'
                    VALUE_NAME: 'websiteImageSHA'
                    TAG: '${{ github.sha }}' 
