name: Update Image Tag in GitOps Repository

on:
  push:
    branches:
      -  main
    paths:
      - 'src/frontend/**'

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v3
            name: Check out code

          - uses: mr-smithers-excellent/docker-build-push@v7
            name: Build & push Docker image
            with:
              image: brunopace85/online-boutique-frontend
              tags: ${{ github.sha }}
              registry: docker.io
              dockerfile: src/frontend/Dockerfile
              directory: src/frontend
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

    imageTag-updater:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        
        - name: Update imageTag
          uses: cheelim1/image-updater@v1.11
          with:
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            REPO_NAME: 'microservices-demo-manifests'
            REPO_OWNER: 'brunopace85'
            FILE_PATH: 'prod/frontend.yaml'
            IMAGE_TAG: ${{ github.sha}}
